begin;
update public.exercises set name_pt = 'Press Pegada Fechada (Barra)' where name_en = 'Close Grip Press (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Press Pegada Fechada (Halter)' where name_en = 'Close Grip Press (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Flexao Pegada Fechada (Peso corporal)' where name_en = 'Close Grip Push Up Off Of A (Bodyweight)' and not is_custom;
update public.exercises set name_pt = 'Abdominal com Pernas na Bola (Peso corporal)' where name_en = 'Crunch Legs On Exercise Ball (Bodyweight)' and not is_custom;
update public.exercises set name_pt = 'Rosca Deitado no Inclinado (Barra)' where name_en = 'Curl Lying Against An Incline (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca Deitado Pegada Fechada na Polia Alta (Polia)' where name_en = 'Lying Close Grip Bar Curl On High Pulley (Cable)' and not is_custom;
update public.exercises set name_pt = 'Extensao de Triceps Deitado Pegada Fechada Atras da Cabeca (Barra)' where name_en = 'Lying Close Grip Triceps Extension Behind The Head (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Press de Triceps Deitado Pegada Fechada ao Queixo (Barra)' where name_en = 'Lying Close Grip Triceps Press To Chin (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Desenvolvimento Militar Unilateral para o Lado (Kettlebell)' where name_en = 'One Arm Military Press To The Side (Kettlebell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Pronada no Banco (Barra)' where name_en = 'Palms Down Wrist Curl Over A Bench (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Pronada no Banco (Halter)' where name_en = 'Palms Down Wrist Curl Over A Bench (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Supinada no Banco (Barra)' where name_en = 'Palms Up Wrist Curl Over A Bench (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Supinada no Banco (Halter)' where name_en = 'Palms Up Wrist Curl Over A Bench (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Extensao de Triceps Pegada Invertida (Polia)' where name_en = 'Reverse Grip Triceps Pushdown (Cable)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Unilateral Pegada Pronada Sentado (Halter)' where name_en = 'Seated One Arm Palms Down Wrist Curl (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Pronada Sentado (Barra)' where name_en = 'Seated Palms Down Wrist Curl (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Rosca de Punho Pegada Pronada Sentado (Halter)' where name_en = 'Seated Palms Down Wrist Curl (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Elevacao Lateral para Frontal (Halter)' where name_en = 'Side Laterals To Front Raise (Dumbbell)' and not is_custom;
update public.exercises set name_pt = 'Supino Declinado Pegada Fechada para Triceps Testa (Barra)' where name_en = 'Decline Close Grip Bench To Skull Crusher (Barbell)' and not is_custom;
update public.exercises set name_pt = 'Press Declinado no Smith (Maquina)' where name_en = 'Decline Smith Press (Machine)' and not is_custom;
commit;
