export type Palette = {
  text: string;
  background: string;
  tint: string;
  icon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  textTertiary: string;
  bgPrimary: string;
  bgAlt: string;
  surface: string;
  surfaceAlt: string;
  border: string;
  borderStrong: string;
  accent: string;
  accentSoft: string;
  accentStrong: string;
  accentLight: string;
  inputBackground: string;
  inputBorder: string;
  tabBarBackground: string;
  overlay: string;
  overlayLight: string;
  success: string;
  successLight: string;
  warning: string;
  warningText: string;
  error: string;
  errorText: string;
  errorSoft: string;
  inputFill: string;
  inputStroke: string;
  chipFill: string;
  chipFillSelected: string;
  chipBorder: string;
  chipBorderSelected: string;
  chipText: string;
  chipTextSelected: string;
  completedFill: string;
  completedBorder: string;
  completedRowBg: string;
  cardBg: string;
  cardBorder: string;
  rowSeparator: string;
  labelMuted: string;
  dangerBorder: string;
  dangerBg: string;
  dangerRemoveBorder: string;
  dangerRemoveBg: string;
  glowCyan: string;
  stopwatchBg: string;
  stopwatchBgActive: string;
  stopwatchBorderActive: string;
  stopwatchText: string;
  stopwatchTextActive: string;
  setTypeWarmup: string;
  setTypeDrop: string;
  setTypeFailure: string;
  exerciseRowBorder: string;
  exerciseRowBg: string;
  chipModeInactiveBg: string;
};

const heavyPalette: Palette = {
  text: '#FFFFFF',
  background: '#000000',
  tint: '#3B82F6',
  icon: '#A1A1AA',
  tabIconDefault: '#71717A',
  tabIconSelected: '#3B82F6',
  textPrimary: '#FFFFFF',
  textSecondary: '#D4D4D8',
  textMuted: '#A1A1AA',
  textTertiary: '#8FA2BA',
  bgPrimary: '#000000',
  bgAlt: '#000000',
  surface: '#111111',
  surfaceAlt: '#18181B',
  border: '#27272A',
  borderStrong: '#3F3F46',
  accent: '#3B82F6',
  accentSoft: '#172554',
  accentStrong: '#1D4ED8',
  accentLight: '#60A5FA',
  inputBackground: '#111111',
  inputBorder: '#27272A',
  tabBarBackground: '#000000',
  overlay: 'rgba(0, 0, 0, 0.88)',
  overlayLight: 'rgba(0, 0, 0, 0.74)',
  success: '#16A34A',
  successLight: '#34D399',
  warning: '#D97706',
  warningText: '#FBBF24',
  error: '#DC2626',
  errorText: '#F87171',
  errorSoft: '#B91C1C',
  inputFill: '#1F2937',
  inputStroke: '#334155',
  chipFill: '#1F2937',
  chipFillSelected: '#122744',
  chipBorder: '#334155',
  chipBorderSelected: '#3B82F6',
  chipText: '#CBD5E1',
  chipTextSelected: '#EAF1FF',
  completedFill: '#1D3550',
  completedBorder: '#3B82F6',
  completedRowBg: '#13273F',
  cardBg: '#111111',
  cardBorder: '#27272A',
  rowSeparator: '#1F2937',
  labelMuted: '#94A3B8',
  dangerBorder: '#7F1D1D',
  dangerBg: '#2A1118',
  dangerRemoveBorder: '#EF4444',
  dangerRemoveBg: '#7F1D1D',
  glowCyan: '#67E8F9',
  stopwatchBg: '#0E2238',
  stopwatchBgActive: '#0D2A45',
  stopwatchBorderActive: '#0EA5E9',
  stopwatchText: '#93C5FD',
  stopwatchTextActive: '#BAE6FD',
  setTypeWarmup: '#FBBF24',
  setTypeDrop: '#F97316',
  setTypeFailure: '#EF4444',
  exerciseRowBorder: '#273247',
  exerciseRowBg: '#0E1726',
  chipModeInactiveBg: '#0F172A',
};

export const Colors: { light: Palette; dark: Palette } = {
  // Keep light available for compatibility while enforcing Heavy OLED visuals app-wide.
  light: heavyPalette,
  dark: heavyPalette,
};
