/**
 * Hevy PT export titles → preferred LyftTrack catalogue English names (#104).
 * Used by import matching so history lands on shared exercises instead of customs.
 */
export const HEVY_TITLE_TO_CATALOG_NAME: Record<string, string> = {
  'agachamento barra': 'Back Squat',
  'agachamento hack maquina': 'Hack Squat',
  'supino barra': 'Barbell Bench Press',
  'supino halter': 'Dumbbell Bench Press',
  'supino inclinado halter': 'Incline Dumbbell Bench Press',
  'supino inclinado na maquina': 'Machine Chest Press',
  'supino sentado maquina': 'Machine Chest Press',
  'barra fixa': 'Pull Up',
  'barra fixa com peso': 'Pull Up',
  'puxada alta maquina': 'Lat Pulldown',
  'puxada alta na polia maquina': 'Lat Pulldown',
  'remada barra': 'Barbell Bent Over Row',
  'remadas dobradas barra': 'Barbell Bent Over Row',
  'remo sentado maquina': 'Seated Cable Row',
  'elevacao lateral halter': 'Dumbbell Lateral Raise',
  'elevacao lateral cabo': 'Cable Lateral Raise',
  'elevacao frontal halter': 'Dumbbell Front Raise',
  'elevacao frontal cabo': 'Cable Front Raise',
  'elevacao pelvica barra': 'Hip Thrust',
  'cadeira extensora maquina': 'Leg Extension',
  'cadeira flexora maquina': 'Leg Curl',
  'mesa flexora maquina': 'Leg Curl',
  'leg press 45 maquina': 'Leg Press',
  'leg press 45o maquina': 'Leg Press',
  'leg press horizontal maquina': 'Leg Press',
  'press de ombros sentada halter': 'Seated Dumbbell Shoulder Press',
  'press de ombros sentada barra': 'Barbell Overhead Press',
  'desenvolvimento de ombros maquina de placas': 'Machine Shoulder Press',
  'rosca direta halter': 'Dumbbell Curl',
  'rosca direta na polia': 'Cable Curl',
  'rosca scott halter': 'Dumbbell Preacher Curl',
  'rosca scott barra': 'Barbell Preacher Curl',
  'rosca martelo halter': 'Dumbbell Hammer Curl',
  'triceps na polia': 'Triceps Pushdown',
  'triceps na polia com corda': 'Rope Triceps Pushdown',
  'triceps testa barra': 'Skull Crusher',
  'crucifixo na polia maquina': 'Cable Chest Fly',
  'crucifixo inclinado': 'Incline Dumbbell Fly',
  'abdominal declinado com peso': 'Decline Crunch',
  'abdominal na maquina': 'Cable Crunch',
  'elevacao de panturrilha em pe maquina': 'Standing Calf Raise',
  'elevacao de panturrilha sentado maquina': 'Seated Calf Raise',
  'peso morto com pernas esticadas': 'Romanian Deadlift',
  'extensao lombar maquina': 'Hyperextension',
  'hiperextensao reversa': 'Hyperextension',
  'aberturas invertidas de ombro posterior na maquina': 'Reverse Pec Deck',
  'puxada com o braco reto corda': 'Straight Arm Pulldown',
};
